language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mihaicolceriu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mihaicolceriu/react-test npm test

after_success:
  - docker build -t mihaicolceriu/multi-client ./client
  - docker build -t mihaicolceriu/multi-nginx ./nginx
  - docker build -t mihaicolceriu/multi-server ./server
  - docker build -t mihaicolceriu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push mihaicolceriu/multi-client
  - docker push mihaicolceriu/multi-nginx
  - docker push mihaicolceriu/multi-server
  - docker push mihaicolceriu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-612736296897
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
